spring:
  application:
    name: dealership
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/dealership}
      auto-index-creation: true
  security:
    user:
      name: user
      password: password
